// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: node.proto

package nodewire

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Node_Identify_FullMethodName = "/ithiltir.node.v1.Node/Identify"
	Node_Metrics_FullMethodName  = "/ithiltir.node.v1.Node/Metrics"
	Node_Static_FullMethodName   = "/ithiltir.node.v1.Node/Static"
	Node_Virt_FullMethodName     = "/ithiltir.node.v1.Node/Virt"
	Node_Connect_FullMethodName  = "/ithiltir.node.v1.Node/Connect"
)

// NodeClient is the client API for Node service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NodeClient interface {
	Identify(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Identity, error)
	Metrics(ctx context.Context, in *Report, opts ...grpc.CallOption) (*Reply, error)
	Static(ctx context.Context, in *Report, opts ...grpc.CallOption) (*Empty, error)
	Virt(ctx context.Context, in *Report, opts ...grpc.CallOption) (*Empty, error)
	// The node opens this stream; Dash sends bounded read-only queries.
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[NodeMessage, DashMessage], error)
}

type nodeClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeClient(cc grpc.ClientConnInterface) NodeClient {
	return &nodeClient{cc}
}

func (c *nodeClient) Identify(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Identity, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Identity)
	err := c.cc.Invoke(ctx, Node_Identify_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) Metrics(ctx context.Context, in *Report, opts ...grpc.CallOption) (*Reply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Reply)
	err := c.cc.Invoke(ctx, Node_Metrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) Static(ctx context.Context, in *Report, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Node_Static_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) Virt(ctx context.Context, in *Report, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Node_Virt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[NodeMessage, DashMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Node_ServiceDesc.Streams[0], Node_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[NodeMessage, DashMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Node_ConnectClient = grpc.BidiStreamingClient[NodeMessage, DashMessage]

// NodeServer is the server API for Node service.
// All implementations must embed UnimplementedNodeServer
// for forward compatibility.
type NodeServer interface {
	Identify(context.Context, *Empty) (*Identity, error)
	Metrics(context.Context, *Report) (*Reply, error)
	Static(context.Context, *Report) (*Empty, error)
	Virt(context.Context, *Report) (*Empty, error)
	// The node opens this stream; Dash sends bounded read-only queries.
	Connect(grpc.BidiStreamingServer[NodeMessage, DashMessage]) error
	mustEmbedUnimplementedNodeServer()
}

// UnimplementedNodeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeServer struct{}

func (UnimplementedNodeServer) Identify(context.Context, *Empty) (*Identity, error) {
	return nil, status.Error(codes.Unimplemented, "method Identify not implemented")
}
func (UnimplementedNodeServer) Metrics(context.Context, *Report) (*Reply, error) {
	return nil, status.Error(codes.Unimplemented, "method Metrics not implemented")
}
func (UnimplementedNodeServer) Static(context.Context, *Report) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Static not implemented")
}
func (UnimplementedNodeServer) Virt(context.Context, *Report) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Virt not implemented")
}
func (UnimplementedNodeServer) Connect(grpc.BidiStreamingServer[NodeMessage, DashMessage]) error {
	return status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedNodeServer) mustEmbedUnimplementedNodeServer() {}
func (UnimplementedNodeServer) testEmbeddedByValue()              {}

// UnsafeNodeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeServer will
// result in compilation errors.
type UnsafeNodeServer interface {
	mustEmbedUnimplementedNodeServer()
}

func RegisterNodeServer(s grpc.ServiceRegistrar, srv NodeServer) {
	// If the following call panics, it indicates UnimplementedNodeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Node_ServiceDesc, srv)
}

func _Node_Identify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).Identify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Node_Identify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).Identify(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_Metrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Report)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).Metrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Node_Metrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).Metrics(ctx, req.(*Report))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_Static_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Report)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).Static(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Node_Static_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).Static(ctx, req.(*Report))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_Virt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Report)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).Virt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Node_Virt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).Virt(ctx, req.(*Report))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NodeServer).Connect(&grpc.GenericServerStream[NodeMessage, DashMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Node_ConnectServer = grpc.BidiStreamingServer[NodeMessage, DashMessage]

// Node_ServiceDesc is the grpc.ServiceDesc for Node service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Node_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ithiltir.node.v1.Node",
	HandlerType: (*NodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Identify",
			Handler:    _Node_Identify_Handler,
		},
		{
			MethodName: "Metrics",
			Handler:    _Node_Metrics_Handler,
		},
		{
			MethodName: "Static",
			Handler:    _Node_Static_Handler,
		},
		{
			MethodName: "Virt",
			Handler:    _Node_Virt_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _Node_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "node.proto",
}
