// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: node.proto

package nodewire

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The JSON report is the existing versioned node payload, preserving integer
// precision, missing fields and validation semantics across both transports.
type Report struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Json          []byte                 `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Report) Reset() {
	*x = Report{}
	mi := &file_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Report) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Report) ProtoMessage() {}

func (x *Report) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Report.ProtoReflect.Descriptor instead.
func (*Report) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{0}
}

func (x *Report) GetJson() []byte {
	if x != nil {
		return x.Json
	}
	return nil
}

type Reply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Json          []byte                 `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reply) Reset() {
	*x = Reply{}
	mi := &file_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reply) ProtoMessage() {}

func (x *Reply) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reply.ProtoReflect.Descriptor instead.
func (*Reply) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{1}
}

func (x *Reply) GetJson() []byte {
	if x != nil {
		return x.Json
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{2}
}

type Identity struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	InstallId       string                 `protobuf:"bytes,1,opt,name=install_id,json=installId,proto3" json:"install_id,omitempty"`
	Created         bool                   `protobuf:"varint,2,opt,name=created,proto3" json:"created,omitempty"`
	ProtocolVersion uint32                 `protobuf:"varint,3,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Identity) Reset() {
	*x = Identity{}
	mi := &file_node_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Identity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Identity) ProtoMessage() {}

func (x *Identity) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Identity.ProtoReflect.Descriptor instead.
func (*Identity) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{3}
}

func (x *Identity) GetInstallId() string {
	if x != nil {
		return x.InstallId
	}
	return ""
}

func (x *Identity) GetCreated() bool {
	if x != nil {
		return x.Created
	}
	return false
}

func (x *Identity) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

type Capabilities struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	PveHistory    bool                   `protobuf:"varint,2,opt,name=pve_history,json=pveHistory,proto3" json:"pve_history,omitempty"`
	HelperVersion string                 `protobuf:"bytes,3,opt,name=helper_version,json=helperVersion,proto3" json:"helper_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Capabilities) Reset() {
	*x = Capabilities{}
	mi := &file_node_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Capabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Capabilities) ProtoMessage() {}

func (x *Capabilities) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Capabilities.ProtoReflect.Descriptor instead.
func (*Capabilities) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{4}
}

func (x *Capabilities) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Capabilities) GetPveHistory() bool {
	if x != nil {
		return x.PveHistory
	}
	return false
}

func (x *Capabilities) GetHelperVersion() string {
	if x != nil {
		return x.HelperVersion
	}
	return ""
}

type HistoryQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          uint32                 `protobuf:"varint,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	Timeframe     string                 `protobuf:"bytes,2,opt,name=timeframe,proto3" json:"timeframe,omitempty"`
	Consolidation string                 `protobuf:"bytes,3,opt,name=consolidation,proto3" json:"consolidation,omitempty"`
	TimeoutMs     uint32                 `protobuf:"varint,4,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryQuery) Reset() {
	*x = HistoryQuery{}
	mi := &file_node_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryQuery) ProtoMessage() {}

func (x *HistoryQuery) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryQuery.ProtoReflect.Descriptor instead.
func (*HistoryQuery) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{5}
}

func (x *HistoryQuery) GetVmId() uint32 {
	if x != nil {
		return x.VmId
	}
	return 0
}

func (x *HistoryQuery) GetTimeframe() string {
	if x != nil {
		return x.Timeframe
	}
	return ""
}

func (x *HistoryQuery) GetConsolidation() string {
	if x != nil {
		return x.Consolidation
	}
	return ""
}

func (x *HistoryQuery) GetTimeoutMs() uint32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type QueryResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Json          []byte                 `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResult) Reset() {
	*x = QueryResult{}
	mi := &file_node_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResult) ProtoMessage() {}

func (x *QueryResult) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResult.ProtoReflect.Descriptor instead.
func (*QueryResult) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{6}
}

func (x *QueryResult) GetJson() []byte {
	if x != nil {
		return x.Json
	}
	return nil
}

func (x *QueryResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type NodeMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Types that are valid to be assigned to Body:
	//
	//	*NodeMessage_Capabilities
	//	*NodeMessage_Result
	//	*NodeMessage_Heartbeat
	Body          isNodeMessage_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeMessage) Reset() {
	*x = NodeMessage{}
	mi := &file_node_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeMessage) ProtoMessage() {}

func (x *NodeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeMessage.ProtoReflect.Descriptor instead.
func (*NodeMessage) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{7}
}

func (x *NodeMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NodeMessage) GetBody() isNodeMessage_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *NodeMessage) GetCapabilities() *Capabilities {
	if x != nil {
		if x, ok := x.Body.(*NodeMessage_Capabilities); ok {
			return x.Capabilities
		}
	}
	return nil
}

func (x *NodeMessage) GetResult() *QueryResult {
	if x != nil {
		if x, ok := x.Body.(*NodeMessage_Result); ok {
			return x.Result
		}
	}
	return nil
}

func (x *NodeMessage) GetHeartbeat() bool {
	if x != nil {
		if x, ok := x.Body.(*NodeMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return false
}

type isNodeMessage_Body interface {
	isNodeMessage_Body()
}

type NodeMessage_Capabilities struct {
	Capabilities *Capabilities `protobuf:"bytes,2,opt,name=capabilities,proto3,oneof"`
}

type NodeMessage_Result struct {
	Result *QueryResult `protobuf:"bytes,3,opt,name=result,proto3,oneof"`
}

type NodeMessage_Heartbeat struct {
	Heartbeat bool `protobuf:"varint,4,opt,name=heartbeat,proto3,oneof"`
}

func (*NodeMessage_Capabilities) isNodeMessage_Body() {}

func (*NodeMessage_Result) isNodeMessage_Body() {}

func (*NodeMessage_Heartbeat) isNodeMessage_Body() {}

type DashMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Types that are valid to be assigned to Body:
	//
	//	*DashMessage_History
	//	*DashMessage_Cancel
	//	*DashMessage_Heartbeat
	Body          isDashMessage_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DashMessage) Reset() {
	*x = DashMessage{}
	mi := &file_node_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DashMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DashMessage) ProtoMessage() {}

func (x *DashMessage) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DashMessage.ProtoReflect.Descriptor instead.
func (*DashMessage) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{8}
}

func (x *DashMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DashMessage) GetBody() isDashMessage_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *DashMessage) GetHistory() *HistoryQuery {
	if x != nil {
		if x, ok := x.Body.(*DashMessage_History); ok {
			return x.History
		}
	}
	return nil
}

func (x *DashMessage) GetCancel() bool {
	if x != nil {
		if x, ok := x.Body.(*DashMessage_Cancel); ok {
			return x.Cancel
		}
	}
	return false
}

func (x *DashMessage) GetHeartbeat() bool {
	if x != nil {
		if x, ok := x.Body.(*DashMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return false
}

type isDashMessage_Body interface {
	isDashMessage_Body()
}

type DashMessage_History struct {
	History *HistoryQuery `protobuf:"bytes,2,opt,name=history,proto3,oneof"`
}

type DashMessage_Cancel struct {
	Cancel bool `protobuf:"varint,3,opt,name=cancel,proto3,oneof"`
}

type DashMessage_Heartbeat struct {
	Heartbeat bool `protobuf:"varint,4,opt,name=heartbeat,proto3,oneof"`
}

func (*DashMessage_History) isDashMessage_Body() {}

func (*DashMessage_Cancel) isDashMessage_Body() {}

func (*DashMessage_Heartbeat) isDashMessage_Body() {}

var File_node_proto protoreflect.FileDescriptor

const file_node_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"node.proto\x12\x10ithiltir.node.v1\"\x1c\n" +
	"\x06Report\x12\x12\n" +
	"\x04json\x18\x01 \x01(\fR\x04json\"\x1b\n" +
	"\x05Reply\x12\x12\n" +
	"\x04json\x18\x01 \x01(\fR\x04json\"\a\n" +
	"\x05Empty\"n\n" +
	"\bIdentity\x12\x1d\n" +
	"\n" +
	"install_id\x18\x01 \x01(\tR\tinstallId\x12\x18\n" +
	"\acreated\x18\x02 \x01(\bR\acreated\x12)\n" +
	"\x10protocol_version\x18\x03 \x01(\rR\x0fprotocolVersion\"p\n" +
	"\fCapabilities\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x1f\n" +
	"\vpve_history\x18\x02 \x01(\bR\n" +
	"pveHistory\x12%\n" +
	"\x0ehelper_version\x18\x03 \x01(\tR\rhelperVersion\"\x86\x01\n" +
	"\fHistoryQuery\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\rR\x04vmId\x12\x1c\n" +
	"\ttimeframe\x18\x02 \x01(\tR\ttimeframe\x12$\n" +
	"\rconsolidation\x18\x03 \x01(\tR\rconsolidation\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x04 \x01(\rR\ttimeoutMs\"7\n" +
	"\vQueryResult\x12\x12\n" +
	"\x04json\x18\x01 \x01(\fR\x04json\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xc4\x01\n" +
	"\vNodeMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12D\n" +
	"\fcapabilities\x18\x02 \x01(\v2\x1e.ithiltir.node.v1.CapabilitiesH\x00R\fcapabilities\x127\n" +
	"\x06result\x18\x03 \x01(\v2\x1d.ithiltir.node.v1.QueryResultH\x00R\x06result\x12\x1e\n" +
	"\theartbeat\x18\x04 \x01(\bH\x00R\theartbeatB\x06\n" +
	"\x04body\"\x9b\x01\n" +
	"\vDashMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12:\n" +
	"\ahistory\x18\x02 \x01(\v2\x1e.ithiltir.node.v1.HistoryQueryH\x00R\ahistory\x12\x18\n" +
	"\x06cancel\x18\x03 \x01(\bH\x00R\x06cancel\x12\x1e\n" +
	"\theartbeat\x18\x04 \x01(\bH\x00R\theartbeatB\x06\n" +
	"\x04body2\xca\x02\n" +
	"\x04Node\x12?\n" +
	"\bIdentify\x12\x17.ithiltir.node.v1.Empty\x1a\x1a.ithiltir.node.v1.Identity\x12<\n" +
	"\aMetrics\x12\x18.ithiltir.node.v1.Report\x1a\x17.ithiltir.node.v1.Reply\x12;\n" +
	"\x06Static\x12\x18.ithiltir.node.v1.Report\x1a\x17.ithiltir.node.v1.Empty\x129\n" +
	"\x04Virt\x12\x18.ithiltir.node.v1.Report\x1a\x17.ithiltir.node.v1.Empty\x12K\n" +
	"\aConnect\x12\x1d.ithiltir.node.v1.NodeMessage\x1a\x1d.ithiltir.node.v1.DashMessage(\x010\x01B9Z7github.com/Ithildur/Ithiltir/internal/nodewire;nodewireb\x06proto3"

var (
	file_node_proto_rawDescOnce sync.Once
	file_node_proto_rawDescData []byte
)

func file_node_proto_rawDescGZIP() []byte {
	file_node_proto_rawDescOnce.Do(func() {
		file_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_node_proto_rawDesc), len(file_node_proto_rawDesc)))
	})
	return file_node_proto_rawDescData
}

var file_node_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_node_proto_goTypes = []any{
	(*Report)(nil),       // 0: ithiltir.node.v1.Report
	(*Reply)(nil),        // 1: ithiltir.node.v1.Reply
	(*Empty)(nil),        // 2: ithiltir.node.v1.Empty
	(*Identity)(nil),     // 3: ithiltir.node.v1.Identity
	(*Capabilities)(nil), // 4: ithiltir.node.v1.Capabilities
	(*HistoryQuery)(nil), // 5: ithiltir.node.v1.HistoryQuery
	(*QueryResult)(nil),  // 6: ithiltir.node.v1.QueryResult
	(*NodeMessage)(nil),  // 7: ithiltir.node.v1.NodeMessage
	(*DashMessage)(nil),  // 8: ithiltir.node.v1.DashMessage
}
var file_node_proto_depIdxs = []int32{
	4, // 0: ithiltir.node.v1.NodeMessage.capabilities:type_name -> ithiltir.node.v1.Capabilities
	6, // 1: ithiltir.node.v1.NodeMessage.result:type_name -> ithiltir.node.v1.QueryResult
	5, // 2: ithiltir.node.v1.DashMessage.history:type_name -> ithiltir.node.v1.HistoryQuery
	2, // 3: ithiltir.node.v1.Node.Identify:input_type -> ithiltir.node.v1.Empty
	0, // 4: ithiltir.node.v1.Node.Metrics:input_type -> ithiltir.node.v1.Report
	0, // 5: ithiltir.node.v1.Node.Static:input_type -> ithiltir.node.v1.Report
	0, // 6: ithiltir.node.v1.Node.Virt:input_type -> ithiltir.node.v1.Report
	7, // 7: ithiltir.node.v1.Node.Connect:input_type -> ithiltir.node.v1.NodeMessage
	3, // 8: ithiltir.node.v1.Node.Identify:output_type -> ithiltir.node.v1.Identity
	1, // 9: ithiltir.node.v1.Node.Metrics:output_type -> ithiltir.node.v1.Reply
	2, // 10: ithiltir.node.v1.Node.Static:output_type -> ithiltir.node.v1.Empty
	2, // 11: ithiltir.node.v1.Node.Virt:output_type -> ithiltir.node.v1.Empty
	8, // 12: ithiltir.node.v1.Node.Connect:output_type -> ithiltir.node.v1.DashMessage
	8, // [8:13] is the sub-list for method output_type
	3, // [3:8] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_node_proto_init() }
func file_node_proto_init() {
	if File_node_proto != nil {
		return
	}
	file_node_proto_msgTypes[7].OneofWrappers = []any{
		(*NodeMessage_Capabilities)(nil),
		(*NodeMessage_Result)(nil),
		(*NodeMessage_Heartbeat)(nil),
	}
	file_node_proto_msgTypes[8].OneofWrappers = []any{
		(*DashMessage_History)(nil),
		(*DashMessage_Cancel)(nil),
		(*DashMessage_Heartbeat)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_node_proto_rawDesc), len(file_node_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_node_proto_goTypes,
		DependencyIndexes: file_node_proto_depIdxs,
		MessageInfos:      file_node_proto_msgTypes,
	}.Build()
	File_node_proto = out.File
	file_node_proto_goTypes = nil
	file_node_proto_depIdxs = nil
}
